apiVersion: v1
kind: Secret
metadata:
  name: pass-secret-name
  namespace: sonarqube
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: sonarqube
type: Opaque
data:
  pass-key: c29uYXJxdWJlLW1vbml0b3JpbmdQYXNzY29kZQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: sonarqube
type: Opaque
data:
  postgresql-postgres-password: c29uYXJxdWJlLXBvc3RncmVzLXBhc3N3b3Jk
  postgresql-password: c29uYXJxdWJlLXBvc3RncmVzLXBhc3N3b3Jk